### PR TITLE
Meter migration fixes

### LINKED ISSUE #865: Error when starting with v1.22.0
When launching the world I encountered several errors during start that canceled the world launch.

Each called meterfield.ts before:

Migrating sourceData, fieldData Object
biography: ""debility: {corrupted: false, cursed: false, encumbered: false, maimed: false, shaken: false, …}edge: 2health: {value: 5, max: 5, min: 0}heart: 1iron: 3legacies: {quests: 0, questsXpSpent: 0, bonds: 0, bondsXpSpent: 0, discoveries: 0, …}momentum: {value: 2, max: 10, min: -6, resetValue: 2}notes: ""shadow: 2spirit: {value: 5, max: 5, min: 0}supply: {value: 5, max: 5, min: 0}wits: 1xp: 0[[Prototype]]: Object 2

TypeError: Failed data migration for CharacterModel: Cannot create property 'resetValue' on number '2'

After the third time it did start. Going back to my notes it seems that the Health, Spirit, and Supply were reset to their original values not the ones I had noted during the end of the session. My momentum was at reset already.

### PR DESCRIPTION
**Pull request by rsek**
resolves #865 

- meters like `health` and `momentum` are now aggressively coerced from numeric values (to prevent other things from reading it as an invalid value and falling back to defaults)
- remove `template.json`, since we don't actually need it anymore :scissors:  we get defaults from the data model now :D

- [x] Update CHANGELOG.md

### CODE REVIEW

File: src/module/actor/subtypes/character.ts [hunk 1]
```diff
@@ -30,15 +29,13 @@ export class CharacterModel extends foundry.abstract.TypeDataModel<
 	async burnMomentum(this: CharacterModel) {
 		if (this.canBurnMomentum) {
 			await this.parent.update({
-				system: { 'momentum.value': this.parent.system.momentum.resetValue }
+				system: { 'momentum.value': this.parent.system.momentumReset }
```
Comment (rsek) [inline src/module/actor/subtypes/character.ts:32]: in the future this will be a 'real' value so that ActiveEffects can override it, but for the moment it's easier for it to be a getter rather than a stored value

**Review by ben — APPROVED** [review]
